version: '3'

services:
  source_postgres:
    image: postgres:17.7
    ports:
      - "5433:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: source_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  destination_postgres:
    image: postgres:17.7
    ports:
      - "5434:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: destination_db
  
  elt_script:
    build:
      context: /elt_script
      dockerfile: Dockerfile
    command: [ "python", "elt_script.py" ]
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - destination_postgres
  
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    command:
      [
        "run",
        "--profiles-dir",
        "/root/.dbt",
        "--project-dir",
        "/dbt"
      ]
    networks:
      - elt_network
    volumes:
      - ./custom_postgres:/dbt
      - C:/Users/USER/.dbt:/root/.dbt # Adjust this path as needed for your environment
    depends_on:
      elt_script:
        condition: service_completed_successfully
    environment:
      DBT_PROFILE: custom_postgres
      DBT_TARGET: dev

networks:
  elt_network:
    driver: bridge

